name: desimoo_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.8.3
  http: ^1.1.0
  shared_preferences: ^2.2.2
  mongo_dart: ^0.10.4
  image_picker: ^1.0.7
  image_cropper: ^8.0.0
  # Updated versions to fix UnmodifiableUint8ListView error
  tflite_flutter: ^0.12.1
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/farmer_cattles.png
    - assets/model/best_float16.tflite
    - assets/model/labels.txt
    - assets/breeds/gir.jpg
    - assets/breeds/kankrej.jpg
    - assets/breeds/deoni.jpg
    - assets/breeds/hariana.jpg
    - assets/breeds/malnad_gidda.jpg
    - assets/breeds/ongole.jpg
    - assets/breeds/rathi.jpg
    - assets/breeds/red_sindhi.jpg
    - assets/breeds/sahiwal.jpg
    - assets/breeds/tharparkar.jpg
    - assets/breeds/banni.jpg
    - assets/breeds/jaffarabadi.jpg
    - assets/breeds/mehsana.jpg
    - assets/breeds/nagpuri.jpg
    - assets/breeds/nili_ravi.jpg
    - assets/breeds/toda.jpg